plugins {
    id 'java'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'br.com.pessoa'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':domain')
    implementation project(':application')

    /*IMPLEMENTACAO SPRING JPA*/
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    /*IMPLEMENTACAO H2*/
    runtimeOnly 'com.h2database:h2'

    /*IMPLEMENTACAO MAPSTRUCT*/
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    /*IMPLEMENTACAO LOMBOK*/
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    /*IMPLEMENTACAO MAPSTRUCT*/
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

    /*IMPLEMENTACAO FEING*/
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

    /*IMPLEMENTACAO SPRING SECURITY*/
    implementation 'org.springframework.boot:spring-boot-starter-security'
    testImplementation 'org.springframework.security:spring-security-test'

    /*IMPLEMENTACAO JWT*/
    implementation 'com.auth0:java-jwt:4.5.0'

    /*IMPLEMENTACAO DO JAKARTA*/
    implementation 'jakarta.servlet:jakarta.servlet-api:6.0.0'

    /*IMPLEMENTACAO FYWAYDB*/
    implementation 'org.flywaydb:flyway-core'


}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:2023.0.0"
        mavenBom "org.springframework.boot:spring-boot-dependencies:3.4.4"
    }
}

test {
    useJUnitPlatform()
}